version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: e-spire-database
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: yvesdsb
      POSTGRES_PASSWORD: esy@rt2332
      POSTGRES_DB: e-spire
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: